### ISSUE TITLE
Sending resources on lower speed links (e.g. LoRa) is very delayed

### ISSUE THREAD

**Issue by jacobeva** [markqvist/Reticulum#569] opened 2024-10-08 13:01 UTC
**Describe the Bug**
This bug was investigated by @liamcottle. I'm writing it up for him.

On lower speed links such as LoRa, sometimes resources are stuck at 100% (on the sender time) and are not finished off for some time. It can take upwards of 5 minutes for the resource to finish sending sometimes.

**To Reproduce**
Use the latest version of Sideband and attempt to send a file to another Sideband instance over LoRa. Keep doing so until one of the file transmissions inevitably gets stuck. It can take a couple files before this happens.

**Expected Behavior**
Files should send correctly and not take some time to finish.

**Logs & Screenshots**
```
Timed out waiting for 1 part, requesting retry
Transfer concluded for LXMF delivery resource <c15aa185341acfdad0b7fcf37241d839262299bfd5e1293fb7ddc1c58f4dbb3d/d88d24aae518cfb14b5fbda89862e86e>
Backchannel became available for <4e9e21b7e64fd18d168220199384bad4> on delivery link <d88d24aae518cfb14b5fbda89862e86e>
```
These timed out errors repeat whilst Sideband tries to finish off transmitting the packet.

@liamcottle "it [the file] does send, it just takes way longer that it should
it goes from 0% to 80% in like a second or so, then maybe 30 seconds later 100%, but then it sets at 100% for several minutes while showing those timeout logs, then it finally comes through on recipient side"

**System Information**
- Android
- Python version
- Version of RNS included on Sideband v1.1.1

**Additional context**
We discussed this in the Matrix chat and it was initially believed that this was due to a bug in the RAK4631 firmware. It turns out that this actually occurs with the Heltec LoRa32 v3 as well, but on this board it seemingly gets stuck for less time.

Downgrading to Sideband 0.9.2 fixes the issue, which uses RNS 0.7.5.

This is potentially related to these commits altering resource behaviour:
https://github.com/markqvist/Reticulum/commit/bd9aa2954bac2f8a5b42a32de7db3401bb166d57
https://github.com/markqvist/Reticulum/commit/53226d70358621e104b71019845402c04444272f

**Comment by markqvist** [comment] 2024-10-08 14:11
@liamcottle, can you provide the LoRa parameters you used here, and also give me an indication of the file size of the file you tried transferring?

When `Timed out waiting for 1 part, requesting retry` is printed in the log, it means that one expected part was not received within the timeout window for this part of the transfer, and that a new part request is sent for that missing part. Were you able to see if:

- That part request packet is actually sent out by the receiving device?
- The part request packet is received on the file sender end?
- A new part is sent out by sender after receiving the packet?

I don't *think* commit https://github.com/markqvist/Reticulum/commit/53226d70358621e104b71019845402c04444272f would be the cause of this, it was actually made to alleviate situations like this, where large part windows on very slow links would make the timeouts excruciatingly long, before a part request retry was made.

In general, the Resource transfers prioritise reliability over speed, so if there's lots of packet loss, it will try to still get the data through, but at the cost of some long waits and timeouts for the retries. This becomes very apparent on very slow links.

There's obviously a balance to be had though ;)

That the retries are repeatedly not met with what should be the last part of the data is kinda the most suspicious thing here. Figuring out why that happens is probably the most sensible approach right now.

**Comment by jacobeva** [comment] 2024-10-08 16:24
I think I see what you mean now. Testing this myself, it seems some packets have HMAC errors, which implies the same corruption from the interface itself that we've been discussing previously. So it potentially *is* related to the issue I was investigating in the firmware. I'll let Liam respond to your questions but we've probably opened this in the wrong repo ;)

**Comment by liamcottle** [comment] 2024-10-09 21:48
> can you provide the LoRa parameters you used here

- Frequency: `917.375 MHz`
- Power: `22dBm`
- Bandwidth: `250 KHz`
- Spreading Factor: `11`
- Coding Rate: `4:5`

> give me an indication of the file size

```
Transfer size is 1.60 KB in 4 parts.
```

Tests were done with images and audio sent from Sideband to MeshChat.

- One of the audio attachments was around `700 bytes`.
- I also tested with `Low Bandwidth Image`, and `Medium Image` from sideband.
- Some of the logs on the receiving side indicated these images were around `1.6KB`.

After testing some experimental firmware changes from @jacobeva, it was noted this issue seems to be fixed. This was while running both RAK4631 RNodes over USB between 2x sideband instances.

However, I do note this issue did come up again (even with the fix) when testing with one RNode connected to Sideband over BLE and the other over USB, so maybe there's a separate issue with BLE...

> Were you able to see if:
>
> That part request packet is actually sent out by the receiving device?
> The part request packet is received on the file sender end?
> A new part is sent out by sender after receiving the packet?

I couldn't see any logs for this, but there was no activity on the RF waterfall for quite some time. However, as mentioned about the custom firmware commits by @jacobeva, there was way more RF activity and the file came through faster.

Still noting the issue seems to still be apparent for BLE though.

> Testing this myself, it seems some packets have HMAC errors

I did see one of the HMAC errors show up (even on the firmware with the fixes), but after a second or two, it seemed to continue on anyway.

```
[Error] Decryption failed on link <305d9fd33b81ba9d6c2b755e29714ef9>. The contained exception was: Token HMAC was invalid
```

**Comment by markqvist** [comment] 2024-10-10 11:12
Actually, there *is* a bug in Reticulum as well! I was just able to replicate it, by adding some synthetic packet drops to the resource transfer code. It happens in quite rare cases where a certain combination of packet loss and link resets leads to very long resource transfer timeouts.

Should have a fix incoming soon :)

**Comment by jacobeva** [comment] 2024-10-10 11:30
Well I never did!

**Comment by markqvist** [comment] 2024-10-10 15:54
Ok, I think I've got this sorted now in https://github.com/markqvist/Reticulum/commit/6521f839cdf9a10e4a21d98cb5963dcf0ad584b8. Thanks for providing the details @liamcottle!

I should have releases out with the fix soon.

**Closed by markqvist** 2024-10-10 15:54 UTC
