### ISSUE TITLE
Autointerface creates unnecessary traffic overhead (optimization necessary)

### ISSUE THREAD

**Issue by SebastianObi** [markqvist/Reticulum#344] opened 2023-07-06 14:08 UTC
I have tested with the auto interface. I noticed that all data is sent to all clients. Although the data is only directed to one destination. This generates significant traffic in the network and should be improved. This can also be seen in the source code that everything is sent to all peers.

```
def processOutgoing(self,data):
            for peer in self.peers:
                try:
                    if self.outbound_udp_socket == None:
                        self.outbound_udp_socket = socket.socket(socket.AF_INET6, socket.SOCK_DGRAM)
                    
                    peer_addr = str(peer)+"%"+str(self.peers[peer][0])
                    addr_info = socket.getaddrinfo(peer_addr, self.data_port, socket.AF_INET6, socket.SOCK_DGRAM)
                    self.outbound_udp_socket.sendto(data, addr_info[0][4])

                except Exception as e:
                    RNS.log("Could not transmit on "+str(self)+". The contained exception was: "+str(e), RNS.LOG_ERROR)

            
            self.txb += len(data)
```

**Comment by markqvist** [comment] 2023-07-09 13:49
This is functioning as intended currently, although it could definitely be improved, and any help in that direction is welcome. That being said, it is a non-trivial problem, which requires **careful consideration**.

Since this ticket is basically just pointing out a known facet of the current implementation, and thus not really providing any value, I will close it for now.

You are however **very** welcome to come up with a detailed analysis of the problem, along with a functional strategy for solving it, and raising that as a new issue. Then we can start working on it.

**Closed by markqvist** 2023-07-09 13:49 UTC
