### ISSUE TITLE
rnsd crash without RNode

### ISSUE THREAD

**Issue by AutumnSpark1226** [markqvist/Reticulum#425] opened 2024-01-14 12:28 UTC
Hello, I have some reticulum applications running on a raspberry pi. I installed the RNode firmware on a LilyGo Lora32 which is usually connected via usb to the pi. That works without any problems. However if I the Lora32 is not connected and I try to start the rnsd daemon I get this message after a few seconds. (This is the output reported via systemctl status)
> Jan 14 13:16:57 server4B4GB rnsd[11360]:     Transport.jobs()
> Jan 14 13:16:57 server4B4GB rnsd[11360]:   File "/home/nomad/.local/lib/python3.11/site-packages/RNS/Transport.py", line 656, in jobs
> Jan 14 13:16:57 server4B4GB rnsd[11360]:     packet.send()
> Jan 14 13:16:57 server4B4GB rnsd[11360]:   File "/home/nomad/.local/lib/python3.11/site-packages/RNS/Packet.py", line 262, in send
> Jan 14 13:16:57 server4B4GB rnsd[11360]:     if RNS.Transport.outbound(self):
> Jan 14 13:16:57 server4B4GB rnsd[11360]:        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Jan 14 13:16:57 server4B4GB rnsd[11360]:   File "/home/nomad/.local/lib/python3.11/site-packages/RNS/Transport.py", line 880, in outbound
> Jan 14 13:16:57 server4B4GB rnsd[11360]:     tx_time   = (len(packet.raw)*8) / interface.bitrate
> Jan 14 13:16:57 server4B4GB rnsd[11360]:                 ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
> Jan 14 13:16:57 server4B4GB rnsd[11360]: ZeroDivisionError: division by zero

This is the output of directly running rnsd:

> 2024-01-14 13:23:53] [Notice] Opening serial port /dev/ttyACM0...
> [2024-01-14 13:23:53] [Error] Could not open serial port for interface RNodeInterface[Lora32]
> [2024-01-14 13:23:53] [Error] The contained exception was: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'
> [2024-01-14 13:23:53] [Error] Reticulum will attempt to bring up this interface periodically
> [2024-01-14 13:23:56] [Notice] Started rnsd version 0.6.9
> [2024-01-14 13:23:58] [Notice] Opening serial port /dev/ttyACM0...
> [2024-01-14 13:23:58] [Error] Error while reconnecting port, the contained exception was: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'
> [2024-01-14 13:24:03] [Notice] Opening serial port /dev/ttyACM0...
> [2024-01-14 13:24:03] [Error] Error while reconnecting port, the contained exception was: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'
> Exception in thread Thread-60 (jobloop):
> Traceback (most recent call last):
>   File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
>     self.run()
>   File "/usr/lib/python3.11/threading.py", line 975, in run
>     self._target(*self._args, **self._kwargs)
>   File "/home/nomad/.local/lib/python3.11/site-packages/RNS/Transport.py", line 302, in jobloop
>     Transport.jobs()
>   File "/home/nomad/.local/lib/python3.11/site-packages/RNS/Transport.py", line 656, in jobs
>     packet.send()
>   File "/home/nomad/.local/lib/python3.11/site-packages/RNS/Packet.py", line 262, in send
>     if RNS.Transport.outbound(self):
>        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/nomad/.local/lib/python3.11/site-packages/RNS/Transport.py", line 880, in outbound
>     tx_time   = (len(packet.raw)*8) / interface.bitrate
>                 ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
> ZeroDivisionError: division by zero
> [2024-01-14 13:24:08] [Notice] Opening serial port /dev/ttyACM0...
> [2024-01-14 13:24:08] [Error] Error while reconnecting port, the contained exception was: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'

After that I can't connect via any other interface, too.

**Comment by Erethon** [comment] 2024-01-14 23:09
I tried recreating this by plugging and unplugging a RNode multiple times, even while the RNode was transmitting packet, but I wasn't able to reproduce this. What kind (board and revision) of an RNode are you running and which version of Reticulum?

**Comment by markqvist** [comment] 2024-01-15 10:24
Also, what version of RNS is this on?

**Comment by markqvist** [comment] 2024-01-15 16:16
Ah, I couldn't understand why I couldn't reproduce this, but it turns out it was already fixed in d67c8eb1cd454d53718c6ef1f281ba2ff4444714, just not released yet ;) Thanks for reporting anyway!

**Closed by markqvist** 2024-01-15 16:16 UTC
